version: '3.7'

services:
  web:
    build:
      context: ./services/web
      dockerfile: Dockerfile.prod
    container_name: gunicorn-server
    command: gunicorn --bind 0.0.0.0:5000 run:app
    expose:
      - 5000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  client:
    build:
      context: ./services/client
      dockerfile: Dockerfile.prod
    container_name: vue-js-client
    volumes:
      - ./client:/app
      - ./client/node_modules:/app/node_modules
    expose:
      - 80
    ports:
      - 80:80
  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  # nginx:
  #   build: ./services/nginx
  #   container_name: nginx
  #   ports:
  #       - 80:80
  #   depends_on:
  #     - web
    

volumes:
  postgres_data: