"""empty message

Revision ID: 6d362c802741
Revises: 0eaa84383350
Create Date: 2020-04-26 17:50:54.583342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d362c802741'
down_revision = '0eaa84383350'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cells', 'pm_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cells', 'pm_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
