"""empty message

Revision ID: 71ee1932fc2d
Revises: 6d362c802741
Create Date: 2020-05-09 15:27:32.803811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71ee1932fc2d'
down_revision = '6d362c802741'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_machines', sa.Column('url', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post_machines', 'url')
    # ### end Alembic commands ###
