"""empty message

Revision ID: 9a8152dc37c3
Revises: c121749a81f1
Create Date: 2020-06-24 14:23:11.019711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a8152dc37c3'
down_revision = 'c121749a81f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('places',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('address', sa.String(length=128), nullable=False),
    sa.Column('org_name', sa.String(length=60), nullable=True),
    sa.Column('bailee', sa.String(length=60), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('comment', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('web_admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=30), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('comment', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clients_places',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('place_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cells',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('isEmpty', sa.Boolean(), nullable=False),
    sa.Column('isRent', sa.Boolean(), nullable=False),
    sa.Column('isMTC', sa.Boolean(), nullable=False),
    sa.Column('pm_id', sa.Integer(), nullable=True),
    sa.Column('temp', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(length=128), nullable=True),
    sa.Column('global_open', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pm_id'], ['post_machines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rented_cells',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cell_id', sa.Integer(), nullable=True),
    sa.Column('date_start', sa.DateTime(), nullable=True),
    sa.Column('date_end', sa.DateTime(), nullable=True),
    sa.Column('comment', sa.String(length=128), nullable=True),
    sa.Column('rentOpen', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cell_id'], ['cells.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('clients', sa.Column('comment', sa.String(length=128), nullable=True))
    op.add_column('clients', sa.Column('keyword', sa.String(length=30), nullable=False))
    op.add_column('clients', sa.Column('last_activity', sa.DateTime(), nullable=True))
    op.add_column('clients', sa.Column('patronymic', sa.String(length=30), nullable=False))
    op.add_column('couriers', sa.Column('comment', sa.String(length=128), nullable=True))
    op.add_column('couriers', sa.Column('keyword', sa.String(length=30), nullable=False))
    op.add_column('couriers', sa.Column('last_activity', sa.DateTime(), nullable=True))
    op.add_column('couriers', sa.Column('patronymic', sa.String(length=30), nullable=False))
    op.add_column('orders', sa.Column('comment', sa.String(length=128), nullable=True))
    op.add_column('post_machines', sa.Column('address', sa.String(length=128), nullable=False))
    op.add_column('post_machines', sa.Column('comment', sa.String(length=128), nullable=True))
    op.add_column('post_machines', sa.Column('factory_num', sa.String(length=35), nullable=True))
    op.add_column('post_machines', sa.Column('place_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'post_machines', ['factory_num'])
    op.create_foreign_key(None, 'post_machines', 'places', ['place_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post_machines', type_='foreignkey')
    op.drop_constraint(None, 'post_machines', type_='unique')
    op.drop_column('post_machines', 'place_id')
    op.drop_column('post_machines', 'factory_num')
    op.drop_column('post_machines', 'comment')
    op.drop_column('post_machines', 'address')
    op.drop_column('orders', 'comment')
    op.drop_column('couriers', 'patronymic')
    op.drop_column('couriers', 'last_activity')
    op.drop_column('couriers', 'keyword')
    op.drop_column('couriers', 'comment')
    op.drop_column('clients', 'patronymic')
    op.drop_column('clients', 'last_activity')
    op.drop_column('clients', 'keyword')
    op.drop_column('clients', 'comment')
    op.drop_table('rented_cells')
    op.drop_table('cells')
    op.drop_table('clients_places')
    op.drop_table('web_admin')
    op.drop_table('places')
    # ### end Alembic commands ###
