"""empty message

Revision ID: c00a1be76057
Revises: 9a8152dc37c3
Create Date: 2020-06-29 12:41:03.287162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c00a1be76057'
down_revision = '9a8152dc37c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('place_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'clients', 'places', ['place_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.drop_column('clients', 'place_id')
    # ### end Alembic commands ###
