#FROM node:10.19.0-alpine as build-stage
FROM node:14.3.0-alpine as build-stage
WORKDIR /app
COPY package*.json ./
RUN yarn
COPY . .
#RUN npm cache clean --force
#RUN rm -rf nodemodules package-lock.json
RUN npm install
RUN npm run build

# Production stage
FROM nginx:1.16.1-alpine as production-stage
COPY --from=build-stage /app/dist /usr/share/nginx/html
EXPOSE 80
CMD [ "nginx", "-g", "daemon off;"]