"""empty message

Revision ID: 7fbccb135a09
Revises: 71ee1932fc2d
Create Date: 2020-05-16 11:04:41.810941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fbccb135a09'
down_revision = '71ee1932fc2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cells', sa.Column('order_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'cells', 'orders', ['order_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cells', type_='foreignkey')
    op.drop_column('cells', 'order_id')
    # ### end Alembic commands ###
