"""empty message

Revision ID: d2b4a3b35cbd
Revises: b7c12f7e7037
Create Date: 2020-04-26 13:34:52.181997

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd2b4a3b35cbd'
down_revision = 'b7c12f7e7037'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('client_id', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('courier_id', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('order_time', sa.DateTime(), nullable=True))
    op.add_column('orders', sa.Column('postmachine_id', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('time_down', sa.DateTime(), nullable=True))
    op.add_column('orders', sa.Column('time_up', sa.DateTime(), nullable=True))
    op.drop_constraint('orders_postMachineId_fkey', 'orders', type_='foreignkey')
    op.drop_constraint('orders_courierId_fkey', 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'post_machines', ['postmachine_id'], ['id'])
    op.create_foreign_key(None, 'orders', 'clients', ['client_id'], ['id'])
    op.create_foreign_key(None, 'orders', 'couriers', ['courier_id'], ['id'])
    op.drop_column('orders', 'timeUp')
    op.drop_column('orders', 'orderTime')
    op.drop_column('orders', 'clientPhone')
    op.drop_column('orders', 'timeDowm')
    op.drop_column('orders', 'postMachineId')
    op.drop_column('orders', 'courierId')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('courierId', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('postMachineId', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('timeDowm', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('clientPhone', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('orderTime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('timeUp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key('orders_courierId_fkey', 'orders', 'couriers', ['courierId'], ['id'])
    op.create_foreign_key('orders_postMachineId_fkey', 'orders', 'post_machines', ['postMachineId'], ['id'])
    op.drop_column('orders', 'time_up')
    op.drop_column('orders', 'time_down')
    op.drop_column('orders', 'postmachine_id')
    op.drop_column('orders', 'order_time')
    op.drop_column('orders', 'courier_id')
    op.drop_column('orders', 'client_id')
    # ### end Alembic commands ###
